name: Auditor√≠a de Calidad (Jacoco)

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # el robot descarga el codigo
    - uses: actions/checkout@v3

    #  instala Java 17 para Spring Boot 3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    #  permiso al robot para ejecutar Gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # Ejecuta los tests y genera el reporte Jacoco
    - name: Build with Gradle and Run Jacoco
      run: ./gradlew test jacocoTestReport build
    
  
    - name: Mensaje Final
      if: success()
      run: echo "Tu codigo paso todas las pruebas "